service: clear-lambda-storage

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.7
  region: ${opt:region, 'us-east-1'}
  logRetentionInDays: 7
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:ListFunctions
        - lambda:ListVersionsByFunction
        - lambda:DeleteFunction
      Resource: "*"

package:
  exclude:
    - .git/**
    - node_modules/**
    - __pycache__/**
    - package-lock.json
    - package.json
    - README.srt

functions:
  clear_lambda_storage:
    handler: clear_lambda_storage.main
    memorySize: 128
    timeout: 900
    events:
      - schedule: rate(1 hour)
